baseurl: "/digitale-leraar" 

repo: "https://github.com/Pius-X-Antwerpen/digitale-leraar" 
prose: "https://prose.io/#Pius-X-Antwerpen/digitale-leraar" 
github_user: "Pius-X-Antwerpen"
github_repo: "digitale-leraar"

collections:
  pages:
    output: true 


defaults:
  - scope:
      path: ""
    values:
      pagetype: article
      layout: "default"

prose:
  rooturl: "_pages"
  siteurl: "https://pius-x-antwerpen.github.io/digitale-leraar"
  media: "assets/images"